CREATE TABLE GUEST(
    SABUN NUMBER(5) PRIMARY KEY, 
    NAME VARCHAR2(30),
    REGDATE DATE,
    PAY NUMBER(20)
);
INSERT INTO GUEST VALUES (1111, 'USER1', SYSDATE - 2, 1000);
INSERT INTO GUEST VALUES (2222, 'USER2', SYSDATE - 1, 2000);
INSERT INTO GUEST VALUES (3333, 'USER3', SYSDATE, 3000);
INSERT INTO GUEST VALUES (4444, 'USER4', SYSDATE, 4000);
COMMIT;
SELECT * FROM GUEST;
SELECT SABUN, NAME, REGDATE, PAY FROM GUEST;

SELECT COUNT(*) AS CNT FROM GUEST;
SELECT NVL(MAX(SABUN),0) + 1111 AS SABUN FROM GUEST;

INSERT INTO GUEST
    (SABUN, NAME, REGDATE, PAY)
VALUES (:SABUN, :NAME, SYSDATE, :PAY);

SELECT * FROM GUEST;
UPDATE GUEST
 SET NAME = 'TEST'
WHERE SABUN = 6666
;





CREATE TABLE GUESTBOOK (
    IDX NUMBER PRIMARY KEY, 
    NAME VARCHAR2(30),
    SUBJECT VARCHAR2(150),
    CONTENT VARCHAR2(4000),
    EMAIL VARCHAR2(100),
    PWD VARCHAR2(30),
    REGDATE DATE DEFAULT SYSDATE
);
CREATE SEQUENCE GUESTBOOK_SEQ NOCACHE;
INSERT INTO GUESTBOOK
        (IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE)
VALUES(GUESTBOOK_SEQ.NEXTVAL, '全老悼', '力格1', '郴侩1',
        'hong1@test.com', '1111', SYSDATE - 3);
INSERT INTO GUESTBOOK
        (IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE)
VALUES(GUESTBOOK_SEQ.NEXTVAL, '全捞悼', '力格2', '郴侩2',
        'hong2@test.com', '2222', SYSDATE - 2); 
INSERT INTO GUESTBOOK
        (IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE)
VALUES(GUESTBOOK_SEQ.NEXTVAL, '全伙悼', '力格3', '郴侩3',
        'hong3@test.com', '3333', SYSDATE - 1);        
COMMIT;

SELECT * FROM GUESTBOOK;

SELECT IDX, NAME, SUBJECT, CONTENT, EMAIL, PWD, REGDATE
 FROM GUESTBOOK
 ORDER BY IDX
;
DELETE FROM GUESTBOOK;